name: hk-rss-daily
on:
  schedule:
    - cron: '15 0 * * *'      # 09:15 KST
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install -r requirements.txt
      - run: python src/collector/rss_collector.py --target hk_it --limit 5 > hk.json
      - uses: actions/upload-artifact@v4
        with: { name: hk-it, path: hk.json }
